language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "willzhang"
  - git config user.email "524869004@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${travic}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/willzhang/willzhang.github.io.git